"""empty message

Revision ID: 49034b940b6c
Revises: 60f14b0fc74d
Create Date: 2021-08-09 14:21:59.004226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49034b940b6c'
down_revision = '60f14b0fc74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
