"""empty message

Revision ID: 756fdc4a08f4
Revises: 5dce27e1b6be
Create Date: 2021-08-01 13:05:11.414758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756fdc4a08f4'
down_revision = '5dce27e1b6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon', sa.Integer(), nullable=True))
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_column('user', 'icon')
    # ### end Alembic commands ###
